packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@better-auth/cli": 1.4.21
  "@better-auth/expo": 1.6.2
  "@better-auth/utils": 0.4.0
  "@eslint/js": ^9.38.0
  "@tailwindcss/postcss": ^4.1.16
  "@tailwindcss/vite": ^4.1.16
  "@tanstack/react-form": ^1.23.8
  "@tanstack/react-query": ^5.90.8
  "@trpc/client": ^11.16.0
  "@trpc/server": ^11.16.0
  "@trpc/tanstack-react-query": ^11.16.0
  "@types/node": ^22.18.12
  "@vitejs/plugin-react": 6.0.1
  better-auth: 1.6.2
  eslint: ^9.38.0
  prettier: ^3.6.2
  superjson: 2.2.6
  tailwindcss: ^4.1.16
  typescript: ^5.9.3
  zod: ^4.3.6
  vite: 8.0.8

catalogs:
  react19:
    "@types/react": ~19.2.10
    "@types/react-dom": ~19.2.0
    react: 19.2.0
    react-dom: 19.2.0

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  "@eslint/core": 0.17.0
  "@tanstack/react-start": ">=1.167.19"
  "@xmldom/xmldom": ">=0.8.12"
  defu: ">=6.1.5"
  devalue: ">=5.6.2"
  drizzle-orm: ">=0.45.2"
  esbuild: ">=0.25.0"
  flatted: ">=3.4.2"
  js-yaml: ">=4.1.1"
  lightningcss: 1.30.2
  lodash: ">=4.18.1"
  kysely: ">=0.28.14"
  minimatch: ">=9.0.7"
  picomatch: ">=4.0.4"
  tar-fs: ">=3.1.2"
  valibot: ">=1.2.0"
  vite: 8.0.8
  yaml: ">=2.8.3"

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
